name: omni_bridge
description: "Omni Bridge: Live AI Translator. A real-time system audio translation application using Windows desktop capture and AI microservices."

repository: https://github.com/Marshal-GG/omni-bridge-translator
issue_tracker: https://github.com/Marshal-GG/omni-bridge-translator/issues

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  provider: 
  http: 
  bitsdojo_window: 
  tray_manager: 
  window_manager: 
  system_tray: 
  flutter_acrylic:
  ffi: ^2.1.5
  web_socket_channel: ^3.0.3
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
